In [42]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('../resources/stack_overflowcsv.csv')
df.head()

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,Country,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary
0,2/28/18 20:20,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,South Africa,NaN,Git,21,13,Male,NaN
1,6/28/18 13:26,Bachelor's degree (BA. BS. B.Eng.. etc.),70841.0,Yes,Sweeden,7.0,Git;Subversion,38,9,Male,"70,841.00"
2,6/6/18 3:37,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,No,Sweeden,8.0,Git,45,11,NaN,NaN
3,5/9/18 1:06,Some college/university study without earning ...,21426.0,Yes,Sweeden,NaN,Zip file back-ups,46,12,Male,"21,426.00"
4,4/12/18 22:41,Bachelor's degree (BA. BS. B.Eng.. etc.),41671.0,Yes,UK,8.0,Git,39,7,Male,"£41,671.00"

In [3]:
df.columns

Index(['SurveyDate', 'FormalEducation', 'ConvertedSalary', 'Hobby', 'Country',
       'StackOverflowJobsRecommend', 'VersionControl', 'Age',
       'Years Experience', 'Gender', 'RawSalary'],
      dtype='str')

In [4]:
print(df.dtypes)

SurveyDate                        str
FormalEducation                   str
ConvertedSalary               float64
Hobby                             str
Country                           str
StackOverflowJobsRecommend    float64
VersionControl                    str
Age                             int64
Years Experience                int64
Gender                            str
RawSalary                         str
dtype: object

# Selecting Specific Data Types

In [5]:
only_ints = df.select_dtypes(include=['int'])
print(only_ints.columns)

Index(['Age', 'Years Experience'], dtype='str')

# Dealing with categorical values

In [6]:
df['Country']

0      South Africa
1           Sweeden
2           Sweeden
3           Sweeden
4                UK
           ...
994          France
995           Spain
996             USA
997         Sweeden
998          Russia
Name: Country, Length: 999, dtype: str

# One hot encoding

In [7]:
pd.get_dummies(df,columns=['Country'],prefix='C')

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary,C_France,C_India,C_Ireland,C_Russia,C_South Africa,C_Spain,C_Sweeden,C_UK,C_USA,C_Ukraine
0,2/28/18 20:20,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,NaN,Git,21,13,Male,NaN,False,False,False,False,True,False,False,False,False,False
1,6/28/18 13:26,Bachelor's degree (BA. BS. B.Eng.. etc.),70841.0,Yes,7.0,Git;Subversion,38,9,Male,"70,841.00",False,False,False,False,False,False,True,False,False,False
2,6/6/18 3:37,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,No,8.0,Git,45,11,NaN,NaN,False,False,False,False,False,False,True,False,False,False
3,5/9/18 1:06,Some college/university study without earning ...,21426.0,Yes,NaN,Zip file back-ups,46,12,Male,"21,426.00",False,False,False,False,False,False,True,False,False,False
4,4/12/18 22:41,Bachelor's degree (BA. BS. B.Eng.. etc.),41671.0,Yes,8.0,Git,39,7,Male,"£41,671.00",False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,10/19/18 13:50,Some college/university study without earning ...,NaN,Yes,NaN,Subversion,45,10,Male,NaN,True,False,False,False,False,False,False,False,False,False
995,4/14/18 15:31,Bachelor's degree (BA. BS. B.Eng.. etc.),58746.0,No,8.0,Git,27,16,Male,"58,746.00",False,False,False,False,False,True,False,False,False,False
996,3/21/18 6:34,Bachelor's degree (BA. BS. B.Eng.. etc.),55000.0,Yes,NaN,Git,54,16,Male,"$55,000.00",False,False,False,False,False,False,False,False,True,False
997,2/5/18 20:01,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,NaN,Git;Subversion,23,9,NaN,NaN,False,False,False,False,False,False,True,False,False,False
998,2/11/18 21:23,Bachelor's degree (BA. BS. B.Eng.. etc.),1000000.0,No,NaN,Git,18,7,NaN,"1,000,000.00",False,False,False,True,False,False,False,False,False,False

# Dummy Encoding

In [17]:
pd.get_dummies(df,columns=['Country'],drop_first=True,prefix='C')
# out = df.filter(regex='^C')
# print

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary,C_India,C_Ireland,C_Russia,C_South Africa,C_Spain,C_Sweeden,C_UK,C_USA,C_Ukraine
0,2/28/18 20:20,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,NaN,Git,21,13,Male,NaN,False,False,False,True,False,False,False,False,False
1,6/28/18 13:26,Bachelor's degree (BA. BS. B.Eng.. etc.),70841.0,Yes,7.0,Git;Subversion,38,9,Male,"70,841.00",False,False,False,False,False,True,False,False,False
2,6/6/18 3:37,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,No,8.0,Git,45,11,NaN,NaN,False,False,False,False,False,True,False,False,False
3,5/9/18 1:06,Some college/university study without earning ...,21426.0,Yes,NaN,Zip file back-ups,46,12,Male,"21,426.00",False,False,False,False,False,True,False,False,False
4,4/12/18 22:41,Bachelor's degree (BA. BS. B.Eng.. etc.),41671.0,Yes,8.0,Git,39,7,Male,"£41,671.00",False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,10/19/18 13:50,Some college/university study without earning ...,NaN,Yes,NaN,Subversion,45,10,Male,NaN,False,False,False,False,False,False,False,False,False
995,4/14/18 15:31,Bachelor's degree (BA. BS. B.Eng.. etc.),58746.0,No,8.0,Git,27,16,Male,"58,746.00",False,False,False,False,True,False,False,False,False
996,3/21/18 6:34,Bachelor's degree (BA. BS. B.Eng.. etc.),55000.0,Yes,NaN,Git,54,16,Male,"$55,000.00",False,False,False,False,False,False,False,True,False
997,2/5/18 20:01,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,NaN,Git;Subversion,23,9,NaN,NaN,False,False,False,False,False,True,False,False,False
998,2/11/18 21:23,Bachelor's degree (BA. BS. B.Eng.. etc.),1000000.0,No,NaN,Git,18,7,NaN,"1,000,000.00",False,False,True,False,False,False,False,False,False

# One - hot vs Dummies
- **One hot encoding** : Explainable features
- **Dummy Encoding** : Necessary information without duplication

# Limiting Columns

In [34]:
counts = df['Country'].value_counts()
print(counts)

mask = df['Country'].isin(counts[counts < 20].index)
df.loc[mask,'Country'] = 'Other'
print(df['Country'].value_counts())

Country
South Africa    166
USA             164
Spain           134
Sweeden         119
France          115
Russia           97
UK               95
India            95
Ukraine           9
Ireland           5
Name: count, dtype: int64
Country
South Africa    166
USA             164
Spain           134
Sweeden         119
France          115
Russia           97
UK               95
India            95
Other            14
Name: count, dtype: int64

In [35]:
import pandas as pd

data = {
    "Restaurant_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Number_of_Violations": [5, 2, 8, 1, 0, 4, 7, 3]
}

df = pd.DataFrame(data)

print(df)

   Restaurant_ID  Number_of_Violations
0            101                     5
1            102                     2
2            103                     8
3            104                     1
4            105                     0
5            106                     4
6            107                     7
7            108                     3

In [39]:
df['Binary_Violation'] = 0

df.loc[df['Number_of_Violations'] > 0 , "Binary_Violation"] = 1

print(df)

   Restaurant_ID  Number_of_Violations  Binary_Violation
0            101                     5                 1
1            102                     2                 1
2            103                     8                 1
3            104                     1                 1
4            105                     0                 0
5            106                     4                 1
6            107                     7                 1
7            108                     3                 1

In [43]:
df['Binned_Group'] = pd.cut(
    df['Number_of_Violations'],
    bins=[-np.inf,0,2,np.inf],
    labels=[1,2,3]
)

df

   Restaurant_ID  Number_of_Violations  Binary_Violation Binned_Group
0            101                     5                 1            3
1            102                     2                 1            2
2            103                     8                 1            3
3            104                     1                 1            2
4            105                     0                 0            1
5            106                     4                 1            3
6            107                     7                 1            3
7            108                     3                 1            3