In [8]:
import pandas as pd
import numpy as np

# What is data preprocessing
- After exploratory data analysis and data cleaning
- Preparing data for modelling
- **Example** : transforming categorical features into numerical features ( dummy variables )

## Why preprocess ?
- Transform dataset so its suitable for modelling
- Improve model performance
- Generate more reliable results

In [19]:
hiking = pd.read_json("../Resources/hiking.json")
wine = pd.read_csv('../Resources/wine_types.csv')
volunteer = pd.read_csv("../Resources/volunteer_opportunities.csv") 
hiking.head()

,Prop_ID,Name,Location,Park_Name,Length,Difficulty,Other_Details,Accessible,Limited_Access,lat,lon
0,B057,Salt Marsh Nature Trail,"Enter behind the Salt Marsh Nature Center, loc...",Marine Park,0.8 miles,NaN,<p>The first half of this mile-long trail foll...,Y,N,NaN,NaN
1,B073,Lullwater,Enter Park at Lincoln Road and Ocean Avenue en...,Prospect Park,1.0 mile,Easy,Explore the Lullwater to see how nature thrive...,N,N,NaN,NaN
2,B073,Midwood,Enter Park at Lincoln Road and Ocean Avenue en...,Prospect Park,0.75 miles,Easy,Step back in time with a walk through Brooklyn...,N,N,NaN,NaN
3,B073,Peninsula,Enter Park at Lincoln Road and Ocean Avenue en...,Prospect Park,0.5 miles,Easy,Discover how the Peninsula has changed over th...,N,N,NaN,NaN
4,B073,Waterfall,Enter Park at Lincoln Road and Ocean Avenue en...,Prospect Park,0.5 miles,Easy,Trace the source of the Lake on the Waterfall ...,N,N,NaN,NaN

In [3]:
hiking.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Prop_ID         33 non-null     str
 1   Name            33 non-null     str
 2   Location        33 non-null     str
 3   Park_Name       33 non-null     str
 4   Length          29 non-null     str
 5   Difficulty      27 non-null     str
 6   Other_Details   31 non-null     str
 7   Accessible      33 non-null     str
 8   Limited_Access  33 non-null     str
 9   lat             0 non-null      float64
 10  lon             0 non-null      float64
dtypes: float64(2), str(9)
memory usage: 14.3 KB

In [4]:
print(wine.describe())

             Type     Alcohol  Malic acid         Ash  Alcalinity of ash  \
count  178.000000  178.000000  178.000000  178.000000         178.000000
mean     1.938202   13.000618    2.336348    2.366517          19.494944
std      0.775035    0.811827    1.117146    0.274344           3.339564
min      1.000000   11.030000    0.740000    1.360000          10.600000
25%      1.000000   12.362500    1.602500    2.210000          17.200000
50%      2.000000   13.050000    1.865000    2.360000          19.500000
75%      3.000000   13.677500    3.082500    2.557500          21.500000
max      3.000000   14.830000    5.800000    3.230000          30.000000

        Magnesium  Total phenols  Flavanoids  Nonflavanoid phenols  \
count  178.000000     178.000000  178.000000            178.000000
mean    99.741573       2.295112    2.029270              0.361854
std     14.282484       0.625851    0.998859              0.124453
min     70.000000       0.980000    0.340000              0.130000
25%     88.000000       1.742500    1.205000              0.270000
50%     98.000000       2.355000    2.135000              0.340000
75%    107.000000       2.800000    2.875000              0.437500
max    162.000000       3.880000    5.080000              0.660000

       Proanthocyanins  Color intensity         Hue  \
count       178.000000       178.000000  178.000000
mean          1.590899         5.058090    0.957449
std           0.572359         2.318286    0.228572
min           0.410000         1.280000    0.480000
25%           1.250000         3.220000    0.782500
50%           1.555000         4.690000    0.965000
75%           1.950000         6.200000    1.120000
max           3.580000        13.000000    1.710000

       OD280/OD315 of diluted wines      Proline
count                    178.000000   178.000000
mean                       2.611685   746.893258
std                        0.709990   314.907474
min                        1.270000   278.000000
25%                        1.937500   500.500000
50%                        2.780000   673.500000
75%                        3.170000   985.000000
max                        4.000000  1680.000000

# Remove Missing data

In [15]:
df = pd.DataFrame({
    'A': [10, np.nan, 30, 40, np.nan, 60, 70],
    'B': [5, 15, np.nan, 35, 45, 55, np.nan],
    'C': [np.nan, 22, 33, np.nan, 55, 66, 77]
})

In [10]:
print(df.dropna())

      A     B     C
5  60.0  55.0  66.0

# Drop Specific Rows

In [12]:
print(df.drop([1,2,3]))

      A     B     C
0  10.0   5.0   NaN
4   NaN  45.0  55.0
5  60.0  55.0  66.0
6  70.0   NaN  77.0

# Drop Columns

In [14]:
print(df.drop("A",axis=1))

      B     C
0   5.0   NaN
1  15.0  22.0
2   NaN  33.0
3  35.0   NaN
4  45.0  55.0
5  55.0  66.0
6   NaN  77.0

# Drop Rows with NAN

In [16]:
df.isna().sum()

A    2
B    2
C    2
dtype: int64

In [17]:
df.dropna(subset=["B"])

      A     B     C
0  10.0   5.0   NaN
1   NaN  15.0  22.0
3  40.0  35.0   NaN
4   NaN  45.0  55.0
5  60.0  55.0  66.0

# minimum number of non-null (non-NA) values required to keep a row or column

In [18]:
print(df.dropna(thresh=2))

      A     B     C
0  10.0   5.0   NaN
1   NaN  15.0  22.0
2  30.0   NaN  33.0
3  40.0  35.0   NaN
4   NaN  45.0  55.0
5  60.0  55.0  66.0
6  70.0   NaN  77.0

In [20]:
volunteer.isna().sum()

opportunity_id          0
content_id              0
vol_requests            0
event_time              0
title                   0
hits                    0
summary                 0
is_priority           603
category_id            48
category_desc          48
amsl                  665
amsl_unit             665
org_title               0
org_content_id          0
addresses_count         0
locality               70
region                  0
postalcode              6
primary_loc           665
display_url             0
recurrence_type         0
hours                   0
created_date            0
last_modified_date      0
start_date_date         0
end_date_date           0
status                  0
Latitude              665
Longitude             665
Community Board       665
Community Council     665
Census Tract          665
BIN                   665
BBL                   665
NTA                   665
dtype: int64

In [22]:
volunteer.columns

Index(['opportunity_id', 'content_id', 'vol_requests', 'event_time', 'title',
       'hits', 'summary', 'is_priority', 'category_id', 'category_desc',
       'amsl', 'amsl_unit', 'org_title', 'org_content_id', 'addresses_count',
       'locality', 'region', 'postalcode', 'primary_loc', 'display_url',
       'recurrence_type', 'hours', 'created_date', 'last_modified_date',
       'start_date_date', 'end_date_date', 'status', 'Latitude', 'Longitude',
       'Community Board', 'Community Council ', 'Census Tract', 'BIN', 'BBL',
       'NTA'],
      dtype='str')

# Working with data types

### Why are types important

In [23]:
print(volunteer.info())

<class 'pandas.DataFrame'>
RangeIndex: 665 entries, 0 to 664
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   opportunity_id      665 non-null    int64
 1   content_id          665 non-null    int64
 2   vol_requests        665 non-null    int64
 3   event_time          665 non-null    int64
 4   title               665 non-null    str
 5   hits                665 non-null    int64
 6   summary             665 non-null    str
 7   is_priority         62 non-null     str
 8   category_id         617 non-null    float64
 9   category_desc       617 non-null    str
 10  amsl                0 non-null      float64
 11  amsl_unit           0 non-null      float64
 12  org_title           665 non-null    str
 13  org_content_id      665 non-null    int64
 14  addresses_count     665 non-null    int64
 15  locality            595 non-null    str
 16  region              665 non-null    str
 17  postalcode          659 non-null    float64
 18  primary_loc         0 non-null      float64
 19  display_url         665 non-null    str
 20  recurrence_type     665 non-null    str
 21  hours               665 non-null    int64
 22  created_date        665 non-null    str
 23  last_modified_date  665 non-null    str
 24  start_date_date     665 non-null    str
 25  end_date_date       665 non-null    str
 26  status              665 non-null    str
 27  Latitude            0 non-null      float64
 28  Longitude           0 non-null      float64
 29  Community Board     0 non-null      float64
 30  Community Council   0 non-null      float64
 31  Census Tract        0 non-null      float64
 32  BIN                 0 non-null      float64
 33  BBL                 0 non-null      float64
 34  NTA                 0 non-null      float64
dtypes: float64(13), int64(8), str(14)
memory usage: 450.1 KB
None

In [33]:
df = pd.DataFrame({
    'A': [10, 5, 30],
    'B': ["string", "string", "string"],
    'C': [2, 10, 33]
})

In [32]:
print(df.info())
print(df)

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      object
 1   B       3 non-null      string
 2   C       3 non-null      object
dtypes: object(2), string(1)
memory usage: 212.0+ bytes
None
        A       B       C
0      10       5       2
1  string  string  string
2      30       2      33

In [35]:
df['B'] =  df["B"].astype("string")
df['A'] =  df["A"].astype("float")
df['C'] =  df["C"].astype("float")

print(df.dtypes)

A    float64
B     string
C    float64
dtype: object

In [36]:
volunteer.info()

<class 'pandas.DataFrame'>
RangeIndex: 665 entries, 0 to 664
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   opportunity_id      665 non-null    int64
 1   content_id          665 non-null    int64
 2   vol_requests        665 non-null    int64
 3   event_time          665 non-null    int64
 4   title               665 non-null    str
 5   hits                665 non-null    int64
 6   summary             665 non-null    str
 7   is_priority         62 non-null     str
 8   category_id         617 non-null    float64
 9   category_desc       617 non-null    str
 10  amsl                0 non-null      float64
 11  amsl_unit           0 non-null      float64
 12  org_title           665 non-null    str
 13  org_content_id      665 non-null    int64
 14  addresses_count     665 non-null    int64
 15  locality            595 non-null    str
 16  region              665 non-null    str
 17  postalcode          659 non-null    float64
 18  primary_loc         0 non-null      float64
 19  display_url         665 non-null    str
 20  recurrence_type     665 non-null    str
 21  hours               665 non-null    int64
 22  created_date        665 non-null    str
 23  last_modified_date  665 non-null    str
 24  start_date_date     665 non-null    str
 25  end_date_date       665 non-null    str
 26  status              665 non-null    str
 27  Latitude            0 non-null      float64
 28  Longitude           0 non-null      float64
 29  Community Board     0 non-null      float64
 30  Community Council   0 non-null      float64
 31  Census Tract        0 non-null      float64
 32  BIN                 0 non-null      float64
 33  BBL                 0 non-null      float64
 34  NTA                 0 non-null      float64
dtypes: float64(13), int64(8), str(14)
memory usage: 450.1 KB

# Training and Test sets

# Why split ?
- Reduces overfitting
- Evaluate performance on a holdout set

In [40]:
from sklearn.model_selection import train_test_split

feature = volunteer.drop("category_desc",axis=1).values
target = volunteer['category_desc'].values

target.value_counts()

Strengthening Communities    307
Environment                   32
Helping Neighbors in Need    119
Health                        52
Education                     92
Emergency Preparedness        15
Name: count, dtype: int64