In [3]:
import pandas as pd
import numpy as np

# How gaps in data occur 
- Data not being collected properly
- Collection and management errors
- Data intentionally being omitted
- Could be created due to transformations of the data

# Why we care ?
- Some models cannot work with missing data (Nulls/Nans)
- Missing data maybe a sign of a wider data issue 
- Missing data maybe useful

In [4]:
df = pd.read_csv('../resources/stack_overflowcsv.csv')
df.head()

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,Country,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary
0,2/28/18 20:20,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,South Africa,NaN,Git,21,13,Male,NaN
1,6/28/18 13:26,Bachelor's degree (BA. BS. B.Eng.. etc.),70841.0,Yes,Sweeden,7.0,Git;Subversion,38,9,Male,"70,841.00"
2,6/6/18 3:37,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,No,Sweeden,8.0,Git,45,11,NaN,NaN
3,5/9/18 1:06,Some college/university study without earning ...,21426.0,Yes,Sweeden,NaN,Zip file back-ups,46,12,Male,"21,426.00"
4,4/12/18 22:41,Bachelor's degree (BA. BS. B.Eng.. etc.),41671.0,Yes,UK,8.0,Git,39,7,Male,"£41,671.00"

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   SurveyDate                  999 non-null    str
 1   FormalEducation             999 non-null    str
 2   ConvertedSalary             665 non-null    float64
 3   Hobby                       999 non-null    str
 4   Country                     999 non-null    str
 5   StackOverflowJobsRecommend  487 non-null    float64
 6   VersionControl              999 non-null    str
 7   Age                         999 non-null    int64
 8   Years Experience            999 non-null    int64
 9   Gender                      693 non-null    str
 10  RawSalary                   665 non-null    str
dtypes: float64(2), int64(2), str(7)
memory usage: 173.4 KB

In [6]:
df.isnull()

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,Country,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary
0,False,False,True,False,False,True,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,True,True
3,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
994,False,False,True,False,False,True,False,False,False,False,True
995,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,True,False,False,False,False,False
997,False,False,True,False,False,True,False,False,False,True,True
998,False,False,False,False,False,True,False,False,False,True,False

In [7]:
df['StackOverflowJobsRecommend'].isnull().sum()

np.int64(512)

In [8]:
df.notnull()

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,Country,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary
0,True,True,False,True,True,False,True,True,True,True,False
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,False,True,True,True,True,True,True,False,False
3,True,True,True,True,True,False,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
994,True,True,False,True,True,False,True,True,True,True,False
995,True,True,True,True,True,True,True,True,True,True,True
996,True,True,True,True,True,False,True,True,True,True,True
997,True,True,False,True,True,False,True,True,True,False,False
998,True,True,True,True,True,False,True,True,True,False,True

# List wise deletion
- If you are confident that the missing values in your dataset are occurring at random, (in other words not being intentionally omitted) the most effective and statistically sound approach to dealing with them is called 'complete case analysis' or listwise deletion. In this method, a record is fully excluded from your model if any of its values are missing.

### Disadvantages
- It deletes valid data points
- Relies on randomness
- Reduces information

In [ ]:
# All columns
df.dropna(how='any')

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,Country,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary
1,6/28/18 13:26,Bachelor's degree (BA. BS. B.Eng.. etc.),70841.0,Yes,Sweeden,7.0,Git;Subversion,38,9,Male,"70,841.00"
4,4/12/18 22:41,Bachelor's degree (BA. BS. B.Eng.. etc.),41671.0,Yes,UK,8.0,Git,39,7,Male,"£41,671.00"
5,2/9/18 19:09,Some college/university study without earning ...,120000.0,Yes,Russia,7.0,Git,39,2,Male,"120,000.00"
7,10/16/18 23:36,Some college/university study without earning ...,250000.0,Yes,France,7.0,Git,24,2,Female,"250,000.00"
17,8/21/18 10:48,Master's degree (MA. MS. M.Eng.. MBA. etc.),51408.0,Yes,USA,9.0,Git;Subversion,55,1,Male,"$51,408.00"
...,...,...,...,...,...,...,...,...,...,...,...
974,2/5/18 0:24,Bachelor's degree (BA. BS. B.Eng.. etc.),125000.0,No,France,10.0,Git,42,15,Male,"125,000.00"
983,5/25/18 8:29,Bachelor's degree (BA. BS. B.Eng.. etc.),90000.0,Yes,Sweeden,5.0,Git,40,2,Male,"90,000.00"
984,7/1/18 12:51,Bachelor's degree (BA. BS. B.Eng.. etc.),70000.0,Yes,India,10.0,Git,46,3,Male,"70,000.00"
993,3/4/18 19:11,Some college/university study without earning ...,30000.0,Yes,India,0.0,Git,28,5,Male,"30,000.00"
995,4/14/18 15:31,Bachelor's degree (BA. BS. B.Eng.. etc.),58746.0,No,Spain,8.0,Git,27,16,Male,"58,746.00"

In [11]:
# Drop rows with missing values in a specific columns
df.dropna(subset=['VersionControl'])

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,Country,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary
0,2/28/18 20:20,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,South Africa,NaN,Git,21,13,Male,NaN
1,6/28/18 13:26,Bachelor's degree (BA. BS. B.Eng.. etc.),70841.0,Yes,Sweeden,7.0,Git;Subversion,38,9,Male,"70,841.00"
2,6/6/18 3:37,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,No,Sweeden,8.0,Git,45,11,NaN,NaN
3,5/9/18 1:06,Some college/university study without earning ...,21426.0,Yes,Sweeden,NaN,Zip file back-ups,46,12,Male,"21,426.00"
4,4/12/18 22:41,Bachelor's degree (BA. BS. B.Eng.. etc.),41671.0,Yes,UK,8.0,Git,39,7,Male,"£41,671.00"
...,...,...,...,...,...,...,...,...,...,...,...
994,10/19/18 13:50,Some college/university study without earning ...,NaN,Yes,France,NaN,Subversion,45,10,Male,NaN
995,4/14/18 15:31,Bachelor's degree (BA. BS. B.Eng.. etc.),58746.0,No,Spain,8.0,Git,27,16,Male,"58,746.00"
996,3/21/18 6:34,Bachelor's degree (BA. BS. B.Eng.. etc.),55000.0,Yes,USA,NaN,Git,54,16,Male,"$55,000.00"
997,2/5/18 20:01,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,Sweeden,NaN,Git;Subversion,23,9,NaN,NaN
998,2/11/18 21:23,Bachelor's degree (BA. BS. B.Eng.. etc.),1000000.0,No,Russia,NaN,Git,18,7,NaN,"1,000,000.00"

### Replacing with strings

In [18]:
# Replace missing values in a specific column
# With a given string

df["VersionControl"].fillna(
    value='None Given',inplace=True
)

/var/folders/6x/cw89xb1x1f7c87g5_m1hrq040000gn/T/ipykernel_64560/1025848051.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["VersionControl"].fillna(

0                    Git
1         Git;Subversion
2                    Git
3      Zip file back-ups
4                    Git
             ...
994           Subversion
995                  Git
996                  Git
997       Git;Subversion
998                  Git
Name: VersionControl, Length: 999, dtype: str

# Recording missing values

In [19]:
df['SalaryGiven'] = df['ConvertedSalary'].notnull()

df.drop(columns=['ConvertedSalary'])

,SurveyDate,FormalEducation,Hobby,Country,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary,SalaryGiven
0,2/28/18 20:20,Bachelor's degree (BA. BS. B.Eng.. etc.),Yes,South Africa,NaN,Git,21,13,Male,NaN,False
1,6/28/18 13:26,Bachelor's degree (BA. BS. B.Eng.. etc.),Yes,Sweeden,7.0,Git;Subversion,38,9,Male,"70,841.00",True
2,6/6/18 3:37,Bachelor's degree (BA. BS. B.Eng.. etc.),No,Sweeden,8.0,Git,45,11,NaN,NaN,False
3,5/9/18 1:06,Some college/university study without earning ...,Yes,Sweeden,NaN,Zip file back-ups,46,12,Male,"21,426.00",True
4,4/12/18 22:41,Bachelor's degree (BA. BS. B.Eng.. etc.),Yes,UK,8.0,Git,39,7,Male,"£41,671.00",True
...,...,...,...,...,...,...,...,...,...,...,...
994,10/19/18 13:50,Some college/university study without earning ...,Yes,France,NaN,Subversion,45,10,Male,NaN,False
995,4/14/18 15:31,Bachelor's degree (BA. BS. B.Eng.. etc.),No,Spain,8.0,Git,27,16,Male,"58,746.00",True
996,3/21/18 6:34,Bachelor's degree (BA. BS. B.Eng.. etc.),Yes,USA,NaN,Git,54,16,Male,"$55,000.00",True
997,2/5/18 20:01,Bachelor's degree (BA. BS. B.Eng.. etc.),Yes,Sweeden,NaN,Git;Subversion,23,9,NaN,NaN,False
998,2/11/18 21:23,Bachelor's degree (BA. BS. B.Eng.. etc.),No,Russia,NaN,Git,18,7,NaN,"1,000,000.00",True

# Fill continuos missing values


### Deleting missing values
- Can't delete rows with missing values in the test set

### What else can you do 
- **Categorical columns** : Replace missing values with the most common occurring value or with a string that flags missing values such as 'None

- **Numeric Columns** : Replace missing values with a suitable value

- In cases like this we can often turn to the measures of central tendency.
- The most common ones are **mean** and **median**
- Similarly, the standard error and test statistics can be incorrectly estimated so if these metrics are needed they should be calculated before the missing values have been filled.

In [20]:
print(df['ConvertedSalary'].mean())
print(df['ConvertedSalary'].median())

92565.16992481203
55562.0

In [22]:
df['ConvertedSalary'] = df['ConvertedSalary'].fillna(
    df['ConvertedSalary'].mean()
)

df['ConvertedSalary'] = df['ConvertedSalary'].astype('int64')

# Dealing with other data items

In [23]:
print(df['RawSalary'].dtype)

str

In [24]:
df['RawSalary'].head()

0           NaN
1     70,841.00
2           NaN
3     21,426.00
4    £41,671.00
Name: RawSalary, dtype: str

In [27]:
df['RawSalary'] = df['RawSalary'].str.replace(',','')
# df['RawSalary'] = df['RawSalary'].astype('float')